name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch: {}

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Enable OCI registry support
        run: |
          helm version
          helm registry login registry-1.docker.io || true
          echo "OCI registry support enabled"

      - name: Build chart dependencies
        run: |
          set -euo pipefail
          for dir in $(find charts -mindepth 1 -maxdepth 1 -type d); do
            if [ -f "$dir/Chart.yaml" ]; then
              echo "Building dependencies for $dir..."
              helm dependency build "$dir"
            fi
          done

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts
          config: .cr.yaml
